name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'  # Ensure this matches the version in your go.mod

    - name: Install dependencies
      run: |
        go mod tidy || true
        go mod download || true

    - name: Build all Go packages
      run: |
        # Find all directories containing Go files and build them
        for dir in $(find . -name '*.go' -exec dirname {} \; | sort -u); do
          echo "Building $dir"
          go build "$dir"
        done
      shell: bash